name: consu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    rame: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test checksum
      run: go test -cover -covermode=atomic -count 1 -coverprofile=coverage_checksum.txt -v ./checksum

    - name: Upload coverage report
      run: |
        echo "" > coverage.txt
        if [ -f coverage_checksum.txt ]; then
          cat coverage_checksum.txt >> coverage.txt
          rm coverage_checksum.txt
        fi
        bash <(curl -s https://codecov.io/bash)
