name: consu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test checksum
      run: cd ./checksum && go test -cover -covermode=atomic -count 1 -coverprofile=../coverage_checksum.txt -v . && cd ..
    - name: Test gjrc
      run: cd ./gjrc && go test -cover -covermode=atomic -count 1 -coverprofile=../coverage_gjrc.txt -v . && cd ..
    - name: Test olaf
      run: cd ./olaf && go test -cover -covermode=atomic -count 1 -coverprofile=../coverage_olaf.txt -v . && cd ..
    - name: Test semita
      run: cd ./semita && go test -cover -covermode=atomic -count 1 -coverprofile=../coverage_semita.txt -v . && cd ..

    - name: Upload coverage report
      run: |
        echo "" > coverage.txt
        echo coverage_*.txt > coverage.txt
        rm -f coverage_*.txt
        bash <(curl -s https://codecov.io/bash)
