name: gjrc

on:
  push:
    branches: [ gjrc ]
  pull_request:
    branches: [ master ]

jobs:
  testGjrc:
    name: TestGjrc
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run test
      run: cd ./gjrc && go test -cover -v -count 1 -p 1 . && cd ..
