name: reddo

on:
  push:
    branches: [ reddo ]
  pull_request:
    branches: [ master ]

jobs:
  testReddo:
    name: TestReddo
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run test
      run: cd ./reddo && go test -cover -coverprofile=../coverage_reddo.txt -v .&& cd ..
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: reddo
        name: reddo
