name: semver

on:
  push:
    branches: [ 'semver', 'dev/semver', 'master' ]
  pull_request:
    types: [ 'closed' ]
    branches: [ 'semver' ]

jobs:
  TestSemver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18', '1.19', '1.20', '1.21', 'stable' ]
    name: Test with Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests
      run: |
        go version
        cd ./semver
        go test -cover -coverprofile=../coverage_semver.txt -v .
        cd ..
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: semver
        name: semver
  
  ReleaseDryRun:
    runs-on: ubuntu-latest
    needs: [ 'TestSemver' ]
    steps:
    - uses: actions/checkout@v3
    - name: Release (dry-run)
      uses: btnguyen2k/action-semrelease@v2
      with:
        dry-run: true
        auto-mode: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag-major-release: false
        tag-minor-release: false
        branches: semver,dev/semver
        tag-prefix: 'semver/v'
