name: semver

on:
  push:
    branches: [ semver ]
  pull_request:
    branches: [ master ]

jobs:
  testSemver:
    name: TestSemver
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run test
      run: cd ./semver && go test -cover -coverprofile=../coverage_semver.txt -v . && cd ..
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: semver
        name: semver
